#!/bin/bash
# PreToolUse guard: deny edits to generated/managed files and point to the right command instead.
input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
case "$file" in
	*routeTree.gen.ts)
		reason="src/routeTree.gen.ts is generated — run 'pnpm generate-routes' (or let the vite plugin regenerate it) instead of editing." ;;
	*/src/paraglide/*)
		reason="src/paraglide/ is generated by the Paraglide vite plugin — edit messages/en.json and messages/de.json instead." ;;
	*pnpm-lock.yaml)
		reason="pnpm-lock.yaml is managed by pnpm — run 'pnpm add' or 'pnpm install' instead of editing." ;;
	*)
		exit 0 ;;
esac
printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}' "$reason"
