/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as VereinRouteImport } from './routes/verein'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TicketbedingungenRouteImport } from './routes/ticketbedingungen'
import { Route as MittelgschaftlerRouteImport } from './routes/mittelgschaftler'
import { Route as LineupRouteImport } from './routes/lineup'
import { Route as InfosRouteImport } from './routes/infos'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HelfenRouteImport } from './routes/helfen'
import { Route as FestivalPolicyRouteImport } from './routes/festival-policy'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AnreiseRouteImport } from './routes/anreise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivIndexRouteImport } from './routes/archiv.index'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as ArchivYearIndexRouteImport } from './routes/archiv.$year.index'
import { Route as ArchivYearArtistsSlugRouteImport } from './routes/archiv.$year.artists.$slug'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinRoute = VereinRouteImport.update({
  id: '/verein',
  path: '/verein',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketbedingungenRoute = TicketbedingungenRouteImport.update({
  id: '/ticketbedingungen',
  path: '/ticketbedingungen',
  getParentRoute: () => rootRouteImport,
} as any)
const MittelgschaftlerRoute = MittelgschaftlerRouteImport.update({
  id: '/mittelgschaftler',
  path: '/mittelgschaftler',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupRoute = LineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosRoute = InfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HelfenRoute = HelfenRouteImport.update({
  id: '/helfen',
  path: '/helfen',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalPolicyRoute = FestivalPolicyRouteImport.update({
  id: '/festival-policy',
  path: '/festival-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AnreiseRoute = AnreiseRouteImport.update({
  id: '/anreise',
  path: '/anreise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivIndexRoute = ArchivIndexRouteImport.update({
  id: '/archiv/',
  path: '/archiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivYearIndexRoute = ArchivYearIndexRouteImport.update({
  id: '/archiv/$year/',
  path: '/archiv/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivYearArtistsSlugRoute = ArchivYearArtistsSlugRouteImport.update({
  id: '/archiv/$year/artists/$slug',
  path: '/archiv/$year/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anreise': typeof AnreiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/festival-policy': typeof FestivalPolicyRoute
  '/helfen': typeof HelfenRoute
  '/impressum': typeof ImpressumRoute
  '/infos': typeof InfosRoute
  '/lineup': typeof LineupRoute
  '/mittelgschaftler': typeof MittelgschaftlerRoute
  '/ticketbedingungen': typeof TicketbedingungenRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/verein': typeof VereinRoute
  '/workshops': typeof WorkshopsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/archiv/': typeof ArchivIndexRoute
  '/archiv/$year/': typeof ArchivYearIndexRoute
  '/archiv/$year/artists/$slug': typeof ArchivYearArtistsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anreise': typeof AnreiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/festival-policy': typeof FestivalPolicyRoute
  '/helfen': typeof HelfenRoute
  '/impressum': typeof ImpressumRoute
  '/infos': typeof InfosRoute
  '/lineup': typeof LineupRoute
  '/mittelgschaftler': typeof MittelgschaftlerRoute
  '/ticketbedingungen': typeof TicketbedingungenRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/verein': typeof VereinRoute
  '/workshops': typeof WorkshopsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/archiv': typeof ArchivIndexRoute
  '/archiv/$year': typeof ArchivYearIndexRoute
  '/archiv/$year/artists/$slug': typeof ArchivYearArtistsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anreise': typeof AnreiseRoute
  '/datenschutz': typeof DatenschutzRoute
  '/festival-policy': typeof FestivalPolicyRoute
  '/helfen': typeof HelfenRoute
  '/impressum': typeof ImpressumRoute
  '/infos': typeof InfosRoute
  '/lineup': typeof LineupRoute
  '/mittelgschaftler': typeof MittelgschaftlerRoute
  '/ticketbedingungen': typeof TicketbedingungenRoute
  '/tickets': typeof TicketsRoute
  '/timetable': typeof TimetableRoute
  '/verein': typeof VereinRoute
  '/workshops': typeof WorkshopsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/archiv/': typeof ArchivIndexRoute
  '/archiv/$year/': typeof ArchivYearIndexRoute
  '/archiv/$year/artists/$slug': typeof ArchivYearArtistsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anreise'
    | '/datenschutz'
    | '/festival-policy'
    | '/helfen'
    | '/impressum'
    | '/infos'
    | '/lineup'
    | '/mittelgschaftler'
    | '/ticketbedingungen'
    | '/tickets'
    | '/timetable'
    | '/verein'
    | '/workshops'
    | '/artists/$slug'
    | '/archiv/'
    | '/archiv/$year/'
    | '/archiv/$year/artists/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anreise'
    | '/datenschutz'
    | '/festival-policy'
    | '/helfen'
    | '/impressum'
    | '/infos'
    | '/lineup'
    | '/mittelgschaftler'
    | '/ticketbedingungen'
    | '/tickets'
    | '/timetable'
    | '/verein'
    | '/workshops'
    | '/artists/$slug'
    | '/archiv'
    | '/archiv/$year'
    | '/archiv/$year/artists/$slug'
  id:
    | '__root__'
    | '/'
    | '/anreise'
    | '/datenschutz'
    | '/festival-policy'
    | '/helfen'
    | '/impressum'
    | '/infos'
    | '/lineup'
    | '/mittelgschaftler'
    | '/ticketbedingungen'
    | '/tickets'
    | '/timetable'
    | '/verein'
    | '/workshops'
    | '/artists/$slug'
    | '/archiv/'
    | '/archiv/$year/'
    | '/archiv/$year/artists/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnreiseRoute: typeof AnreiseRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FestivalPolicyRoute: typeof FestivalPolicyRoute
  HelfenRoute: typeof HelfenRoute
  ImpressumRoute: typeof ImpressumRoute
  InfosRoute: typeof InfosRoute
  LineupRoute: typeof LineupRoute
  MittelgschaftlerRoute: typeof MittelgschaftlerRoute
  TicketbedingungenRoute: typeof TicketbedingungenRoute
  TicketsRoute: typeof TicketsRoute
  TimetableRoute: typeof TimetableRoute
  VereinRoute: typeof VereinRoute
  WorkshopsRoute: typeof WorkshopsRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ArchivIndexRoute: typeof ArchivIndexRoute
  ArchivYearIndexRoute: typeof ArchivYearIndexRoute
  ArchivYearArtistsSlugRoute: typeof ArchivYearArtistsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein': {
      id: '/verein'
      path: '/verein'
      fullPath: '/verein'
      preLoaderRoute: typeof VereinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticketbedingungen': {
      id: '/ticketbedingungen'
      path: '/ticketbedingungen'
      fullPath: '/ticketbedingungen'
      preLoaderRoute: typeof TicketbedingungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mittelgschaftler': {
      id: '/mittelgschaftler'
      path: '/mittelgschaftler'
      fullPath: '/mittelgschaftler'
      preLoaderRoute: typeof MittelgschaftlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup': {
      id: '/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof LineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos': {
      id: '/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof InfosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helfen': {
      id: '/helfen'
      path: '/helfen'
      fullPath: '/helfen'
      preLoaderRoute: typeof HelfenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival-policy': {
      id: '/festival-policy'
      path: '/festival-policy'
      fullPath: '/festival-policy'
      preLoaderRoute: typeof FestivalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anreise': {
      id: '/anreise'
      path: '/anreise'
      fullPath: '/anreise'
      preLoaderRoute: typeof AnreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/': {
      id: '/archiv/'
      path: '/archiv'
      fullPath: '/archiv/'
      preLoaderRoute: typeof ArchivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/$year/': {
      id: '/archiv/$year/'
      path: '/archiv/$year'
      fullPath: '/archiv/$year/'
      preLoaderRoute: typeof ArchivYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/$year/artists/$slug': {
      id: '/archiv/$year/artists/$slug'
      path: '/archiv/$year/artists/$slug'
      fullPath: '/archiv/$year/artists/$slug'
      preLoaderRoute: typeof ArchivYearArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnreiseRoute: AnreiseRoute,
  DatenschutzRoute: DatenschutzRoute,
  FestivalPolicyRoute: FestivalPolicyRoute,
  HelfenRoute: HelfenRoute,
  ImpressumRoute: ImpressumRoute,
  InfosRoute: InfosRoute,
  LineupRoute: LineupRoute,
  MittelgschaftlerRoute: MittelgschaftlerRoute,
  TicketbedingungenRoute: TicketbedingungenRoute,
  TicketsRoute: TicketsRoute,
  TimetableRoute: TimetableRoute,
  VereinRoute: VereinRoute,
  WorkshopsRoute: WorkshopsRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  ArchivIndexRoute: ArchivIndexRoute,
  ArchivYearIndexRoute: ArchivYearIndexRoute,
  ArchivYearArtistsSlugRoute: ArchivYearArtistsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
